### PR TITLE
Allow a delay for running custom scripts after start up

### PR DESCRIPTION
**Pull request by jensmoes**
This can be useful for various purposes. Notably if you need to ensure everything has been initialized before you run your custom code.

### CODE REVIEW

**Comment by PoltoS** [comment]
This is a bad idea, since Z-Wave dongle can be plugged at any time and your code should not rely on just time delay. It is suggested to rely only on events in the system like ZWave.register event

**Comment by jensmoes** [comment]
Then the place to run the custom code needs to be changed. Because now it
is run before the devices have been created so it is a rather useless
component :)

sent from my mobile device

**Comment by jensmoes** [comment]
Is there an event sent out when the registration is complete so one can be sure everything has been initialized and is ready to go?

**Comment by PoltoS** [comment]
Everything? no. What means everything is you can configure it further?

There is events like ZWave.register that fires on Z-Wave engine start.

We will probably add a special CustomZWaveCode module that solves your problem

**Pull request closed without merging**
