### PR TITLE
Fix default WebSocket notifications.

### PR DESCRIPTION
**Pull request by pathec**
I have developed a WebSocket client for Java and have never received the default messages. After the changes I get the default messages. If the original code works with someone, please let me know. 

I also wrote a message in the [forum](https://forum.z-wave.me/viewtopic.php?f=3419&t=22347&start=10#p64402).

### CODE REVIEW

**Comment by ronie-z-wave** [comment]
@PoltoS think thats something that need to be approved by you

**Comment by PoltoS** [comment]
It was not. We have a discussion on the forum about that

**Comment by pathec** [comment]
I've created a new post on this topic. Another test with a **JavaScript** client also receive no messages. If someone has a working code example, please let me know.

I've developed an app for Z-Way and used the corrected version with another message type and data to push all device state updates to the client. All works fine for me.

**Comment by PoltoS** [comment]
Indeed, you are right, the API chaned. Thanks for your contribution!

**Pull request merged**
