### PR TITLE
Remove code that sets ThermostatMode when setting the ThermostatSetPoint

### PR DESCRIPTION
**Pull request by bytedreamer**
Setting the ThermostatMode when updating the ThermostatSetPoint causes problems on my thermostat device. My 2gig CT100 has an Auto thermostat mode. I typically will keep it a Auto throughout the year, and change the temperature based on a schedule. The old code would update the thermostat to an unwanted mode. 

The problem would also be with thermostats with two ThermostatSetPoints. There is a use case where both set points are changed on a schedule. The changing of the set point values shouldn't cause the thermostat mode to be changed.

### CODE REVIEW

**Comment by pz1** [comment]
> The changing of the set point values shouldn't cause the thermostat mode to be changed.

Agree. (That is what Smarthome does in latest release. Expert UI thermostat section has become disfunctional in the meantime.)

I fear that things being done in *Smarthome* are tresspassing on what should be done in *home automation*. We urgently need an **N-State (mode) switch** in home automation as requested in [Issue 80](https://github.com/Z-Wave-Me/home-automation/issues/80)

**Comment by ronie-z-wave** [comment]
Is there still some activity here or in progress?

**Comment by pz1** [comment]
Since they were removed from EUI, I still no longer have a place to set temperature values for respectively comfort/heat save in either EUI or SUI for my StellaZ devices. At present I "poke" the values manually via the webbrowser, which is a bit clumsy. Fortunately I don't need to set them frequently.

**Comment by ronie-z-wave** [comment]
@PoltoS  do you think it's worth or make sense to adjust this like in https://github.com/Z-Wave-Me/home-automation/pull/281/commits/67cfc223c7dad0e7cd4f23ea2d6ca799171f4ff5 ??

**Comment by PoltoS** [comment]
We can remove this once we have a discrete vDev for mode switching

**Comment by ronie-z-wave** [comment]
So we need vDev logic in ZWave module for that, right?
Are there already some concepts or ideas for this?

**Pull request closed without merging**
