### PR TITLE
AeonMultiSensor Module

### PR DESCRIPTION
**Pull request by islipfd19**
Please consider merging this module. I've recently broken out the language to comply with the current standard and created an icon similar to the ones in use. The module takes advantage of the 4 in 1 Aeotec Multi Sensor, a specific case in use is the ability to control the lights on a dimmable switch and set it at a specific level depending on the luminosity and time of day. it also allows to control other binary switch; i.e. if the humidity level reaches a certain low or high point, it may turn on an exhaust fan and turn it off. I've been using this module without any issues.

### CODE REVIEW

**Comment by pz1** [comment]
Why not first publish this module on the forum **recipes section** along with the other userModules?

**Comment by islipfd19** [comment]
Sure I can do that

**Comment by PoltoS** [comment]
Agree. And meanwhile we are working on the "store", so you will be able to upload it yourself in future.

**Comment by islipfd19** [comment]
OK, looking forward to it. Will there be any type of limitations on the store or checking? I know it's off topic, but a poorly written module or a simple mistake can render z-way useless until the module has been manually removed. I've experienced that in the past when writing modules.

**Comment by PoltoS** [comment]
Please separate it into fixes of our code and your authored modules. The latter will go into our new app (modules) store soon.

**Comment by PoltoS** [comment]
Please separate this pull request into different modules:

- AeonMultiSensor - should go to developers.z-wave.me
- Barometer - should go to developers.z-wave.me
- BatteryPolling - is it really worth to notify on >20%? If you feel this to be important, we can cherry-pick this commit
- DoorsPolling - should go to developers.z-wave.me
- Email - should be renamed to something like EmailWithSendmail (not to take Email name for a pretty specific non-crossplatform module) and go to developers.z-wave.me

Thanks a lot for your contribution! Hope our new developers.z-wave.me will be a good place to share your work.

**Comment by islipfd19** [comment]
When time permits, please provide the method to add the modules to the app store so I can submit the new modules.

Email will be updated to EmailWithSendmail

**Comment by pz1** [comment]
It is at http://developer.z-wave.me. In the top left corner is a question mark that you can click for instructions

**Pull request closed without merging**
