### PR TITLE
Added sunset / sunrise information

### PR DESCRIPTION
**Pull request by manyosit**
Added check for sunset / sunrise time and create a second virtual device to indicate whether daylight is currently available or not.

### CODE REVIEW

**Comment by jhmartin** [comment]
Can this be merged?

**Comment by pz1** [comment]
For consideration: There is an excellent [DayLight userModule](http://forum.z-wave.me/viewtopic.php?f=3424&t=21029), which calculates sunrise/set on the basis of geo-position. It supports Official, Civil, Naval, and Astronomical [*)](https://en.wikipedia.org/wiki/Twilight) calculations. Would be worthwhile to take that module in the standard collection

**Comment by PoltoS** [comment]
Isn't it worth to make config param in the module to enable/disable this day/night switch?

**Comment by vipcon** [comment]
Sure, a switch can be added. Does it make sense to have a switch to decide if a switch is generated? Also why calculating the values if they are returned by the openweather request anyway. Just wondering.

**Comment by pz1** [comment]
> Also why calculating the values if they are returned by the openweather request anyway. Just wondering.

DayLight module serves those applications that can't depend on live remote services for whatever (personal) reason.

**Comment by vipcon** [comment]
Understood, but the Openweather API returns the values anyway. So in my point of view it makes sense to use them if weather data is requested.

**Comment by PoltoS** [comment]
Is it possible to update to merge with the current develop code?

**Comment by PoltoS** [comment]
Will this be updated or we can close it?

**Comment by ronie-z-wave** [comment]
Is there still some activity here?

**Comment by pz1** [comment]
@ronie-z-wave 
Apparantly not much activity. I have looked a bit deeper into the module. As far as I understand the day/night flag is only updated at the moment fresh weather data are grabbed. That happens every hour. From the day/night discussions I learned this imprecision would not be acceptable for many users....

**Comment by ronie-z-wave** [comment]
Hi @manyosit,

Unfortunately we've not merged you pull request. But I've adjusted it a bit and fit it in the current version of the module. I've also added a checkbox to make this widget optional.

Please have a look at https://github.com/Z-Wave-Me/home-automation/commit/dd37b67f381a4cad8c2a1d7a1625f825aa683dcd

Thx for support!

**Pull request closed without merging**
