### PR TITLE
Add delayed update as "then" option

### PR DESCRIPTION
**Pull request by i8beef**
This pull request adds an option for a "then" to not only set a static level on another device, but to trigger a poll for the devices state after a configured delay. Also allows for a "scene" based "then" to execute after a delay rather than immediately.

### CODE REVIEW

**Comment by i8beef** [comment]
Note: I did not know how to translate the three new language entries to their respective languages.

**Comment by ronie-z-wave** [comment]
On the develop branch of home-automation the IfThen app has changed, so your pull request will have conflicts. Please use develop branch, have look at the conflicts and make a new pull request of it.

In future please use develop branch for your pull requests.

Thanks for support  :+1:

**Comment by i8beef** [comment]
Well, unfortunately making the changes against the develop branch wasn't an option for me given that I was running on the release out of master, and it's unlikely I'll be able to do so in the future either. Guess I'll just cannibalize it into my own module. If you feel like stealing the idea for yourselves at some point in the future feel free.

**Comment by ronie-z-wave** [comment]
Ok, we keep that in mind ;)

**Pull request closed without merging**
